spring:
   datasource:
    url: jdbc:mysql://localhost:3306/prismamysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    username: root
jpa:
   show-sql: true
#   database-platform: org.hibernate.dialect.MySQL5Dialect
#   generate-ddl: true
#   hibernate:
#    ddl-auto: update
#   properties:
#    hibernate:
#     format_sql: true
     
server:
  port: 8081
  error: 
   include-exception: true
   include-stacktrace: always