spring:
   jpa:
     database: mysql
     show-sql: true
     hibernate:
#        generate-ddl: true
        ddl-auto: update
     database-platform: org.hibernate.dialect.MySQL5Dialect
#  ?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC 
   datasource:
    url: jdbc:mysql://localhost:3306/prismamysql?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    username: root
   thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/ #视图解析器的前缀放在这个文件夹
    suffix: .html #后缀
    enabled: false
   web:
     resources:
       static-locations: file:src/main/java/resources/static/
       cache:
        period: 0
   autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
    
#   main:      
#      web-application-type: none     
#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
#spring.devtools.restart.exclude: WEB-INF/**
     
server:
  port: 8082
  error: 
   whitelabel:
     enabled: false
   include-exception: true
   include-stacktrace: always

debug: true
logging:
  level:
   org:
    springframework:
     boot:
      autoconfigure: INFO
#logging：
#     level：
#     org：
#      springframework：
#      boot：
#      autoconfigure：error  